

import { Tool } from './types.ts';

export const SUPABASE_URL = 'https://tppghsndtbdsdgolpbbh.supabase.co';
export const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRwcGdoc25kdGJkc2Rnb2xwYmJoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyMDE4MTAsImV4cCI6MjA2Nzc3NzgxMH0.gOa_df0VrCWHHunbOUuFNh7PESwrIWHTaCG2jEs9U9Y';

export const TOOLS: Tool[] = [
  // --- Tier 1: Core Student Workflow ---
  {
    id: 'interactive-quiz-builder',
    title: 'Interactive Quiz Builder',
    description: 'Create quizzes with multiple question types.',
    icon: 'extension',
    path: '/interactive-quiz-builder',
  },
  {
    id: 'quiz-whiz',
    title: 'QuizWhiz',
    description: 'Create quizzes from notes or topics.',
    icon: 'quiz',
    path: '/quiz-whiz',
  },
  {
    id: 'essay-buddy',
    title: 'Essay Buddy',
    description: 'Plan your thesis, outline, and intro.',
    icon: 'edit',
    path: '/essay-buddy',
  },
  {
    id: 'smart-notes',
    title: 'SmartNotes',
    description: 'Auto-summarize & explain complex text.',
    icon: 'lightbulb',
    path: '/smart-notes',
  },
  {
    id: 'audio-notes',
    title: 'Audio Notes',
    description: 'Record your voice, get a transcript, and AI-powered notes.',
    icon: 'mic',
    path: '/audio-notes',
  },
  {
    id: 'math-mentor',
    title: 'Math Mentor',
    description: 'Get step-by-step solutions for math problems.',
    icon: 'functions',
    path: '/math-mentor',
  },
  {
    id: 'citation-wizard',
    title: 'Citation Wizard',
    description: 'Generate bibliographies from your text.',
    icon: 'format_quote',
    path: '/citation-wizard',
  },
  {
    id: 'assignment-deconstructor',
    title: 'Assignment Deconstructor',
    description: 'Break down complex assignment prompts.',
    icon: 'segment',
    path: '/assignment-deconstructor',
  },
  {
    id: 'concept-cracker',
    title: 'Concept Cracker',
    description: 'Simplify topics in multiple styles.',
    icon: 'psychology',
    path: '/concept-cracker',
  },
  {
    id: 'multi-doc-synthesizer',
    title: 'The Synthesizer',
    description: 'Combine notes from multiple sources into one summary.',
    icon: 'merge_type',
    path: '/multi-doc-synthesizer',
  },
  {
    id: 'focus-sprint-planner',
    title: 'Focus Sprint Planner',
    description: 'Plan structured study sessions.',
    icon: 'timer',
    path: '/focus-sprint-planner',
  },
  {
    id: 'presentation-rehearsal-coach',
    title: 'Presentation Rehearsal Coach',
    description: 'Get feedback on your presentation delivery.',
    icon: 'record_voice_over',
    path: '/presentation-rehearsal-coach',
  },
  {
    id: 'group-project-coordinator',
    title: 'Group Project Coordinator',
    description: 'Unify tone and check for gaps in group work.',
    icon: 'group_work',
    path: '/group-project-coordinator',
  },
  // --- Tier 2: Teacher's Toolkit ---
  {
    id: 'rubric-builder',
    title: 'Rubric Builder',
    description: 'For Teachers: Quickly generate grading rubrics.',
    icon: 'rule',
    path: '/rubric-builder',
    role: 'teacher',
  },
  {
    id: 'lesson-plan-variator',
    title: 'Lesson Plan Variator',
    description: 'For Teachers: Create dynamic lesson plans.',
    icon: 'dynamic_feed',
    path: '/lesson-plan-variator',
    role: 'teacher',
  },
   {
    id: 'differentiated-text-generator',
    title: 'Differentiated Text Generator',
    description: 'For Teachers: Adapt texts for different reading levels.',
    icon: 'difference',
    path: '/differentiated-text-generator',
    role: 'teacher',
  },
  {
    id: 'student-misconception-spotter',
    title: 'Student Misconception Spotter',
    description: 'For Teachers: Predict common student errors.',
    icon: 'psychology_alt',
    path: '/student-misconception-spotter',
    role: 'teacher',
  },
   {
    id: 'parent-communication-assistant',
    title: 'Parent Communication Assistant',
    description: 'For Teachers: Draft emails to parents.',
    icon: 'forward_to_inbox',
    path: '/parent-communication-assistant',
    role: 'teacher',
  },
  {
    id: 'report-card-generator',
    title: 'Report Card Generator',
    description: 'Generate formal report card comments.',
    icon: 'grading',
    path: '/report-card-generator',
    role: 'teacher',
  },
  {
    id: 'icebreaker-prompter',
    title: 'Icebreaker Prompter',
    description: 'Generate fun icebreakers for any class.',
    icon: 'groups',
    path: '/icebreaker-prompter',
    role: 'teacher',
  },
  // --- Tier 3: Advanced & Specialized Student Tools ---
  {
    id: 'source-credibility-checker',
    title: 'Source Credibility Checker',
    description: "Analyze an article's bias and reliability.",
    icon: 'fact_check',
    path: '/source-credibility-checker',
  },
  {
    id: 'critical-thinking-booster',
    title: 'Critical Thinking Booster',
    description: 'Strengthen your arguments with critique.',
    icon: 'psychology',
    path: '/critical-thinking-booster',
  },
  {
    id: 'textbook-buddy',
    title: 'Textbook Buddy',
    description: 'Digest and get insights from text excerpts.',
    icon: 'menu_book',
    path: '/textbook-buddy',
  },
  {
    id: 'flashcard-generator',
    title: 'Flashcard Generator',
    description: 'Turn your notes into interactive flashcards.',
    icon: 'style',
    path: '/flashcard-generator',
  },
  {
    id: 'doubt-bot',
    title: 'DoubtBot',
    description: 'Get instant answers and further reading.',
    icon: 'chat',
    path: '/doubt-bot',
  },
  {
    id: 'study-plan-ai',
    title: 'StudyPlan AI',
    description: 'Generate a personalized study schedule.',
    icon: 'calendar_today',
    path: '/study-plan-ai',
  },
  {
    id: 'presentation-generator',
    title: 'Presentation Generator',
    description: 'Generate slide content for any topic.',
    icon: 'slideshow',
    path: '/presentation-generator',
  },
  {
    id: 'data-storyteller',
    title: 'Data Storyteller',
    description: 'Get a narrative interpretation of data.',
    icon: 'bar_chart',
    path: '/data-storyteller',
  },
   {
    id: 'visual-data-interpreter',
    title: 'Visual Data Interpreter',
    description: 'Get an AI analysis of a chart or graph.',
    icon: 'insights',
    path: '/visual-data-interpreter',
  },
  {
    id: 'lab-helper',
    title: 'LabHelper',
    description: 'Explain experiments, safety, and purpose.',
    icon: 'science',
    path: '/lab-helper',
  },
  {
    id: 'code-explainer',
    title: 'Code Explainer',
    description: 'Get simple, line-by-line code explanations.',
    icon: 'code',
    path: '/code-explainer',
  },
  {
    id: 'scholarship-coach',
    title: 'Scholarship Coach',
    description: 'Draft & improve your scholarship essays.',
    icon: 'school',
    path: '/scholarship-coach',
  },
  {
    id: 'resume-rewriter',
    title: 'Resume Rewriter',
    description: 'Improve your resume for clarity and impact.',
    icon: 'article',
    path: '/resume-rewriter',
  },
  {
    id: 'internship-email-assistant',
    title: 'Internship Email Assistant',
    description: 'Draft professional emails for networking & jobs.',
    icon: 'email',
    path: '/internship-email-assistant',
  },
  {
    id: 'career-mapper',
    title: 'Career Path Mapper',
    description: 'Map career paths from your interests.',
    icon: 'map',
    path: '/career-mapper',
  },
  {
    id: 'debate-assistant',
    title: 'Debate Prep Assistant',
    description: 'Generate pro/con arguments for any topic.',
    icon: 'gavel',
    path: '/debate-assistant',
  },
  {
    id: 'mnemonic-maker',
    title: 'Mnemonic Maker',
    description: 'Create memory aids for lists or concepts.',
    icon: 'psychology_alt',
    path: '/mnemonic-maker',
  },
  {
    id: 'project-brainstormer',
    title: 'Project Brainstormer',
    description: 'Get unique project ideas and research questions.',
    icon: 'emoji_objects',
    path: '/project-brainstormer',
  },
  {
    id: 'analogy-generator',
    title: 'Analogy Generator',
    description: 'Understand concepts with creative comparisons.',
    icon: 'compare_arrows',
    path: '/analogy-generator',
  },
  {
    id: 'learning-converter',
    title: 'Learning Converter',
    description: 'Adapt explanations to your learning style.',
    icon: 'swap_horiz',
    path: '/learning-converter',
  },
  {
    id: 'historical-context-bot',
    title: 'Historical Context Bot',
    description: "Understand the 'big picture' behind any historical event.",
    icon: 'history_edu',
    path: '/historical-context-bot',
  },
  {
    id: 'ethical-dilemma-explorer',
    title: 'Ethical Dilemma Explorer',
    description: 'Explore moral problems from multiple viewpoints.',
    icon: 'balance',
    path: '/ethical-dilemma-explorer',
  },
  {
    id: 'literary-device-finder',
    title: 'Literary Device Finder',
    description: 'Identify metaphors, similes, and more in texts.',
    icon: 'local_florist',
    path: '/literary-device-finder',
  },
  {
    id: 'keyword-extractor',
    title: 'Keyword Extractor',
    description: 'Extract keywords & definitions from notes.',
    icon: 'label',
    path: '/keyword-extractor',
  },
  {
    id: 'discussion-assistant',
    title: 'Discussion Assistant',
    description: 'Get help with discussion board posts.',
    icon: 'forum',
    path: '/discussion-assistant',
  },
  {
    id: 'text-simplifier',
    title: 'Text Simplifier',
    description: 'Rewrite complex text for ESL students.',
    icon: 'translate',
    path: '/text-simplifier',
  },
  {
    id: 'time-estimator',
    title: 'Time Estimator',
    description: 'Estimate the time required for assignments.',
    icon: 'timer',
    path: '/time-estimator',
  },
  {
    id: 'anxiety-coach',
    title: 'Exam Anxiety Coach',
    description: 'Get calming techniques for test anxiety.',
    icon: 'self_improvement',
    path: '/anxiety-coach',
  },
  {
    id: 'course-outliner',
    title: 'CourseOutliner',
    description: 'Generate a curriculum from a topic.',
    icon: 'view_list',
    path: '/course-outliner',
  },
  {
    id: 'daily-learner',
    title: 'Daily 5-Min Learner',
    description: 'Get a bite-sized lesson on any subject.',
    icon: 'local_library',
    path: '/daily-learner',
  },
   {
    id: 'assignment-formatter',
    title: 'Assignment Formatter',
    description: 'Format your papers in APA, MLA, etc.',
    icon: 'format_align_left',
    path: '/assignment-formatter',
  },
];